### ISSUE TITLE
请问什么叫借标注？

### ISSUE THREAD

**Issue by wxlearncoding** [jiangjiawen/labelme-for-dicom#1]
请问您在功能中的借标注指的是什么？（小白求指导，感谢。）

**Comment by jiangjiawen** [comment]
因为一般医疗图像都是连续的，可以先标注一张，左右两边和这张相差不大。那么当处在未标注的左右两边的时候，就可以用那个按钮把那张已标注的复制过来。最好要当前要复制的是没标注的也就是没有json文件，然后复制过来之后动一下再保存就会生成当前标注的json文件了。前提条件是你打开的是一个系列连续的dicom文件夹。

**Comment by wxlearncoding** [comment]
> 因为一般医疗图像都是连续的，可以先标注一张，左右两边和这张相差不大。那么当处在未标注的左右两边的时候，就可以用那个按钮把那张已标注的复制过来。最好要当前要复制的是没标注的也就是没有json文件，然后复制过来之后动一下再保存就会生成当前标注的json文件了。前提条件是你打开的是一个系列连续的dicom文件夹。

**Comment by wxlearncoding** [comment]
感谢作者回答！
